// <auto-generated />
using System;
using EntityFrameworkCore.MySql.SimpleBulks.Demo;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EntityFrameworkCore.MySql.SimpleBulks.Demo.Migrations
{
    [DbContext(typeof(DemoDbContext))]
    partial class DemoDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("EntityFrameworkCore.MySql.SimpleBulks.Demo.Entities.CompositeKeyRow", b =>
                {
                    b.Property<int>("Id1")
                        .HasColumnType("int");

                    b.Property<int>("Id2")
                        .HasColumnType("int");

                    b.Property<int>("Column1")
                        .HasColumnType("int");

                    b.Property<string>("Column2")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("Column3")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id1", "Id2");

                    b.ToTable("CompositeKeyRows");
                });

            modelBuilder.Entity("EntityFrameworkCore.MySql.SimpleBulks.Demo.Entities.ConfigurationEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("Id1");

                    b.Property<DateTimeOffset>("CreatedDateTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsSensitive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Key")
                        .HasColumnType("longtext")
                        .HasColumnName("Key1");

                    b.Property<DateTime?>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp(6)");

                    b.Property<DateTimeOffset?>("UpdatedDateTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Value")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("ConfigurationEntries");
                });

            modelBuilder.Entity("EntityFrameworkCore.MySql.SimpleBulks.Demo.Entities.Row", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Column1")
                        .HasColumnType("int");

                    b.Property<string>("Column2")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("Column3")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("Decimal")
                        .HasColumnType("decimal(65,30)");

                    b.Property<double>("Double")
                        .HasColumnType("double");

                    b.Property<float>("Float")
                        .HasColumnType("float");

                    b.Property<long>("Long")
                        .HasColumnType("bigint");

                    b.Property<short>("Short")
                        .HasColumnType("smallint");

                    b.HasKey("Id");

                    b.ToTable("Rows");
                });
#pragma warning restore 612, 618
        }
    }
}
