namespace EntityFrameworkCore.MySql.SimpleBulks;

public static class Constants
{
    public const string AutoGeneratedIndexNumberColumn = "AutoGeneratedIndexNumberColumn";
    public const string DefaultCollation = "utf8mb4_0900_ai_ci";
    public const string BeginQuote = "`";
    public const string EndQuote = "`";
}
