name: .Net Build EntityFrameworkCore.MySql.SimpleBulks

on:
  push:
    paths: 
      - 'src/**'
  pull_request:
    paths: 
      - 'src/**'
  workflow_dispatch:
  
jobs:
  build:

    defaults: 
      run:
        working-directory: src
        
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
  
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 8.0.100

    - name: Test
      run: dotnet test EntityFrameworkCore.MySql.SimpleBulks.Tests/EntityFrameworkCore.MySql.SimpleBulks.Tests.csproj /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura

    - name: Build
      run: dotnet build EntityFrameworkCore.MySql.SimpleBulks/EntityFrameworkCore.MySql.SimpleBulks.csproj --configuration Release

    - name: Upload EntityFrameworkCore.MySql.SimpleBulks
      uses: actions/upload-artifact@v4
      with:
        name: EntityFrameworkCore.MySql.SimpleBulks
        path: src/EntityFrameworkCore.MySql.SimpleBulks/bin/Release/*.nupkg
